### ISSUE TITLE
Unable to upgrade from 13.0.2

### ISSUE THREAD

**Issue by michaelquist** [YunoHost-Apps/nextcloud_ynh#136]
Attempting to upgrade fails with the following output:

 11:57:03,390 SUCCESS  yunohost.app success - [627.128] The application list yunohost has been fetched
    2018-09-09 11:57:12,042 SUCCESS  yunohost.app success - [627.128] The application list community has been fetched
    2018-09-09 11:57:12,461 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 11:57:12] "PUT /update HTTP/1.1" 200 209 23.924159
    2018-09-09 11:57:42,097 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 11:57:42,100 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 11:57:42,213 INFO     moulinette.actionsmap process - processing action [627.129]: yunohost.user.list
    2018-09-09 11:57:42,218 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 11:57:42] "GET /users?locale=en HTTP/1.1" 200 320 0.122016
    2018-09-09 11:57:43,593 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 11:57:43,595 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 11:57:43,706 INFO     moulinette.actionsmap process - processing action [627.130]: yunohost.tools.diagnosis
    2018-09-09 11:57:46,760 ERROR    moulinette.core translate - unable to retrieve key 'service_description_pihole-FTL' for default locale 'en'
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 268, in wrapper
        curr_v = params[k]
    KeyError: 'locale'
    2018-09-09 11:57:52,469 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 11:57:52] "GET /diagnosis?locale=en HTTP/1.1" 200 1510 8.877792
    2018-09-09 12:04:38,479 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:04:38,481 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:04:38,619 INFO     moulinette.actionsmap process - processing action [627.131]: yunohost.app.list
    2018-09-09 12:04:39,159 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 12:04:39] "GET /apps?installed&locale=en HTTP/1.1" 200 713 0.681529
    2018-09-09 12:04:41,536 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:04:41,537 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:04:41,650 INFO     moulinette.actionsmap process - processing action [627.132]: yunohost.app.info
    2018-09-09 12:04:41,801 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 12:04:41] "GET /apps/nextcloud?raw&locale=en HTTP/1.1" 200 3285 0.266958
    2018-09-09 12:04:48,321 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:04:48,324 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:04:48,435 INFO     moulinette.actionsmap process - processing action [627.133]: yunohost.app.debug
    2018-09-09 12:04:48,907 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 12:04:48] "GET /apps/nextcloud/debug?locale=en HTTP/1.1" 400 151 0.587790
    2018-09-09 12:04:57,596 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:04:57,598 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:04:57,713 INFO     moulinette.actionsmap process - processing action [627.134]: yunohost.user.list
    2018-09-09 12:04:57,719 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 12:04:57] "GET /users?locale=en HTTP/1.1" 200 320 0.124746
    2018-09-09 12:04:59,017 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:04:59,019 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:04:59,133 INFO     moulinette.actionsmap process - processing action [627.135]: yunohost.tools.diagnosis
    2018-09-09 12:05:02,199 ERROR    moulinette.core translate - unable to retrieve key 'service_description_pihole-FTL' for default locale 'en'
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 268, in wrapper
        curr_v = params[k]
    KeyError: 'locale'
    2018-09-09 12:05:07,967 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 12:05:07] "GET /diagnosis?locale=en HTTP/1.1" 200 1510 8.951575
    2018-09-09 12:05:07,974 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:05:07,977 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:05:08,090 INFO     moulinette.actionsmap process - processing action [627.136]: yunohost.tools.update
    2018-09-09 12:05:15,676 SUCCESS  yunohost.app success - [627.136] The application list yunohost has been fetched
    2018-09-09 12:05:19,833 SUCCESS  yunohost.app success - [627.136] The application list community has been fetched
    2018-09-09 12:05:20,248 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 12:05:20] "PUT /update HTTP/1.1" 200 209 12.274651
    2018-09-09 12:05:58,807 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:05:58,809 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:05:58,928 INFO     moulinette.actionsmap process - processing action [627.137]: yunohost.app.upgrade
    2018-09-09 12:05:59,501 INFO     yunohost.app app_upgrade - [627.137] Upgrading apps nextcloud
    2018-09-09 12:05:59,503 INFO     yunohost.app app_upgrade - [627.137] Upgrading app nextcloud...
    2018-09-09 12:06:19,106 WARNING  yunohost.hook <lambda> - [627.137] mysqldump: Got error: 1045: "Access denied for user 'root'@'localhost' (using password: YES)" when trying to connect
    2018-09-09 12:06:19,111 WARNING  yunohost.hook <lambda> - [627.137] !!
    2018-09-09 12:06:19,113 WARNING  yunohost.hook <lambda> - [627.137]   nextcloud's script has encountered an error. Its execution was cancelled.
    2018-09-09 12:06:19,115 WARNING  yunohost.hook <lambda> - [627.137] !!
    2018-09-09 12:06:19,116 WARNING  yunohost.hook <lambda> - [627.137] 
    2018-09-09 12:06:19,218 WARNING  yunohost.hook <lambda> - [627.137] Unable to back up the app 'nextcloud'
    2018-09-09 12:06:19,220 WARNING  yunohost.hook <lambda> - [627.137] There is nothing to save
    2018-09-09 12:06:19,323 WARNING  yunohost.hook <lambda> - [627.137] Backup failed, the upgrade process was aborted.
    2018-09-09 12:06:19,427 ERROR    yunohost.app app_upgrade - [627.137] Unable to upgrade nextcloud
    2018-09-09 12:06:19,433 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 12:06:19] "PUT /upgrade/apps?app=nextcloud HTTP/1.1" 500 152 20.626720
    2018-09-09 12:06:46,978 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 12:06:46] "GET /version?locale=en HTTP/1.1" 200 355 1.321267
    2018-09-09 12:06:46,986 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:06:46,988 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:06:47,104 INFO     moulinette.actionsmap process - processing action [627.138]: yunohost.user.list
    2018-09-09 12:06:47,110 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 12:06:47] "GET /users?locale=en HTTP/1.1" 200 320 0.124036
    2018-09-09 12:06:47,353 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:06:47,355 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:06:47,464 INFO     moulinette.actionsmap process - processing action [627.139]: yunohost.tools.diagnosis
    2018-09-09 12:06:51,093 ERROR    moulinette.core translate - unable to retrieve key 'service_description_pihole-FTL' for default locale 'en'
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 268, in wrapper
        curr_v = params[k]
    KeyError: 'locale'
    2018-09-09 12:06:56,814 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 12:06:56] "GET /diagnosis?locale=en HTTP/1.1" 200 1510 9.461580
    2018-09-09 12:06:56,823 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:06:56,825 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:06:56,934 INFO     moulinette.actionsmap process - processing action [627.140]: yunohost.tools.update
    2018-09-09 12:07:04,940 SUCCESS  yunohost.app success - [627.140] The application list yunohost has been fetched
    2018-09-09 12:07:09,754 SUCCESS  yunohost.app success - [627.140] The application list community has been fetched
    2018-09-09 12:07:10,166 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2018-09-09 12:07:10] "PUT /update HTTP/1.1" 200 209 13.343255
    2018-09-09 12:07:13,774 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:07:13,777 WARNING  moulinette.authenticator.ldap is_authenticated - Error during ldap authentication process: 'NoneType' object has no attribute 'whoami_s'
    2018-09-09 12:07:13,894 INFO     moulinette.actionsmap process - processing action [627.141]: yunohost.tools.upgrade
    2018-09-09 12:07:15,068 INFO     yunohost.app app_upgrade - [627.141] Upgrading apps description, license, installed, label, id, name
    2018-09-09 12:07:15,070 INFO     yunohost.app app_upgrade - [627.141] Upgrading app libresonic...
    2018-09-09 12:07:15,193 INFO     yunohost.app app_upgrade - [627.141] Upgrading app nextcloud...
    2018-09-09 12:07:34,681 WARNING  yunohost.hook <lambda> - [627.141] mysqldump: Got error: 1045: "Access denied for user 'root'@'localhost' (using password: YES)" when trying to connect
    2018-09-09 12:07:34,687 WARNING  yunohost.hook <lambda> - [627.141] !!
    2018-09-09 12:07:34,689 WARNING  yunohost.hook <lambda> - [627.141]   nextcloud's script has encountered an error. Its execution was cancelled.
    2018-09-09 12:07:34,691 WARNING  yunohost.hook <lambda> - [627.141] !!
    2018-09-09 12:07:34,692 WARNING  yunohost.hook <lambda> - [627.141] 
    2018-09-09 12:07:34,794 WARNING  yunohost.hook <lambda> - [627.141] Unable to back up the app 'nextcloud'
    2018-09-09 12:07:34,796 WARNING  yunohost.hook <lambda> - [627.141] There is nothing to save
    2018-09-09 12:07:34,899 WARNING  yunohost.hook <lambda> - [627.141] Backup failed, the upgrade process was aborted.
    2018-09-09 12:07:35,002 ERROR    yunohost.app app_upgrade - [627.141] Unable to upgrade nextcloud
    2018-09-09 12:07:35,004 INFO     yunohost.app app_upgrade - [627.141] Upgrading app pihole...
    2018-09-09 12:07:35,156 WARNING  yunohost.tools tools_upgrade - [627.141] unable to upgrade apps: [Errno 61] No app to upgrade
    2018-09-09 12:07:35,157 ERROR    yunohost.tools tools_upgrade - [627.141] Unable to upgrade some applications

**Comment by JimboJoe** [comment]
```
2018-09-09 12:06:19,106 WARNING yunohost.hook - [627.137] mysqldump: Got error: 1045: "Access denied for user 'root'@'localhost' (using password: YES)" when trying to connect
```
Looks like your MySQL root password got changed...
Could you please follow [this related forum thread](https://forum.yunohost.org/t/mysql-root-user-is-being-denied-permission-while-installing-an-app/1508) and report here?

Thanks!

**Comment by michaelquist** [comment]
Ok, I have got it working following the advice in that forum thread. This seems to be what it took to fix:

1 . Stop mysql service

service mysql stop

2 . Start to MySQL server w/o password:
use mysqld_safe:

mysqld_safe --skip-grant-tables &

Output:

170403 17:38:46 mysqld_safe Logging to '/var/lib/mysql/domain.com.err'.
170403 17:38:46 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql

3 . Connect to mysql server using mysql client:

# mysql -u root

Output:

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2
Server version: 10.0.30-MariaDB-0+deb8u1 (Debian)

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>

4 . Setup new MySQL root user password

mysql> use mysql;
mysql> update user set password=PASSWORD("**NEW-ROOT-PASSWORD**") where User='root';
mysql> flush privileges;
mysql> quit

5.  sudo nano /etc/yunohost/mysql (edit password here to match new password from step 4)

6.  sudo yunohost service regen-conf mysql -f

7.  Start MySQL server and test it:

service mysql start
mysql -u root -p

8.  reboot
