### ISSUE TITLE
Upgrade fails because of apps like external_user

### ISSUE THREAD

**Issue by gnouts** [YunoHost-Apps/nextcloud_ynh#164]
Hi,
I tried multiple time upgrading from v13.0.6, with command : 
```
sudo yunohost app upgrade nextcloud -u https://github.com/YunoHost-Apps/nextcloud_ynh
```
Here is some relevant log : 
```
2019-02-21 23:16:37,747: DEBUG - An unhandled exception has been thrown:
2019-02-21 23:16:37,747: WARNING -     0/0 [>---------------------------]   0%Unable to upgrade Nextcloud
2019-02-21 23:16:37,747: DEBUG - Error: Call to undefined method GuzzleHttp\Client::request() in /var/www/nextcloud/lib/private/Http/Client/Client.php:161
2019-02-21 23:16:37,747: WARNING - !!
2019-02-21 23:16:37,747: DEBUG - Stack trace:
2019-02-21 23:16:37,748: WARNING -   nextcloud's script has encountered an error. Its execution was cancelled.
2019-02-21 23:16:37,748: DEBUG - #0 /var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php(106): OC\Http\Client\Client->get('https://apps.ne...', Array)
2019-02-21 23:16:37,748: WARNING - !!
2019-02-21 23:16:37,748: DEBUG - #1 /var/www/nextcloud/lib/private/App/AppStore/Fetcher/AppFetcher.php(80): OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
2019-02-21 23:16:37,748: WARNING - Upgrade failed.
2019-02-21 23:16:37,748: DEBUG - #2 /var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php(170): OC\App\AppStore\Fetcher\AppFetcher->fetch('', '')
2019-02-21 23:16:37,748: DEBUG - #3 /var/www/nextcloud/lib/private/Installer.php(385): OC\App\AppStore\Fetcher\Fetcher->get()
2019-02-21 23:16:37,748: DEBUG - #4 /var/www/nextcloud/lib/private/Updater.php(445): OC\Installer->isUpdateAvailable('activity')
2019-02-21 23:16:37,748: DEBUG - #5 /var/www/nextcloud/lib/private/Updater.php(256): OC\Updater->upgradeAppStoreApps(Array)
2019-02-21 23:16:37,748: DEBUG - #6 /var/www/nextcloud/lib/private/Updater.php(126): OC\Updater->doUpgrade('14.0.0.19', '13.0.6.1')
2019-02-21 23:16:37,748: DEBUG - #7 /var/www/nextcloud/core/Command/Upgrade.php(262): OC\Updater->upgrade()
2019-02-21 23:16:37,748: DEBUG - #8 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(251): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2019-02-21 23:16:37,748: DEBUG - #9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2019-02-21 23:16:37,748: DEBUG - #10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2019-02-21 23:16:37,749: DEBUG - #11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2019-02-21 23:16:37,749: DEBUG - #12 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2019-02-21 23:16:37,749: DEBUG - #13 /var/www/nextcloud/console.php(96): OC\Console\Application->run()
2019-02-21 23:16:37,749: DEBUG - #14 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
2019-02-21 23:16:37,749: DEBUG - #15 {main}+ [[ 1 -eq 3 ]]
2019-02-21 23:16:37,749: DEBUG - + ynh_die 'Unable to upgrade Nextcloud'
2019-02-21 23:16:37,749: DEBUG - + echo 'Unable to upgrade Nextcloud'
2019-02-21 23:16:37,749: DEBUG - + exit 1
```

**Comment by Mickael-Martin** [comment]
Hi.
Try to disable yours apps, upgrade nextcloud, then upgrade and enable again yours apps with my post https://github.com/YunoHost-Apps/nextcloud_ynh/pull/152#issuecomment-465226619

**Comment by tomdereub** [comment]
Hi, same problem for me, and the solution worked: I disabled my apps and it worked after disabling 
External user support.
Thanks !

**Comment by alexAubin** [comment]
Those stuff are worrysome ... Can't we find a trick to disable apps before the upgrade ? (Or are they already supposed to be disabled somehow ?)

Apparently there might be a way to know if an extension is compatible with nextcloud using that kind of info : 

```
grep -n "max-version" /var/www/nextcloud/apps/*/appinfo/info.xml
grep -n "max-version" /var/www/nextcloud/apps/*/appinfo/info.xml | grep -v 'max-version="15"'
```

**Comment by gnouts** [comment]
Hi, it worked indeed. Thanks !
But beware if you have **files_external_gdrive** apps enabled. Disabling it crashed my nextcloud instantly.
Related issue : https://help.nextcloud.com/t/google-drive-external-files-0-2-8-app-suspected-of-involvement-in-my-php-fatal-error-sev-1/32494
I had to move/delete the app folder under /var/www/nextcloud/apps/files_external_gdrive to access my cloud again.

**Comment by alexAubin** [comment]
Bump about this, there regurlarly are people on the forum having this issue, typically with user_external : https://forum.yunohost.org/t/update-de-nextcloud-impossible/7357 :/

**Comment by maniackcrudelis** [comment]
Is there a recommended way to handle apps in nextcloud ?
I'm quite surprised that Nextcloud doesn't handle that itself during its upgrade.

**Comment by Mickael-Martin** [comment]
Actually, I prefer use the updater.phar (include apps updates) : `sudo -u www-data php updater.phar`
For me, it's a simple way : no timeout, apps upgrade, step retrying, etc.

**Comment by JimboJoe** [comment]
Fixed by https://github.com/YunoHost-Apps/nextcloud_ynh/pull/169

**Comment by alexAubin** [comment]
>Fixed by #169

Uh but turns out that #169 has been closed before merging ? (Today another user experience this issue ...)

**Comment by alexAubin** [comment]
Well apparently the fix is in https://github.com/YunoHost-Apps/nextcloud_ynh/pull/170 instead ?

**Comment by JimboJoe** [comment]
You're right, it's in #170 and the PR is pending...

**Comment by gnouts** [comment]
This can be closed. PR reached master months ago :)
