### ISSUE TITLE
Upgrade Nextcloud 18.0.2 to 18.0.4 fails

### ISSUE THREAD

**Issue by 1989gironimo** [YunoHost-Apps/nextcloud_ynh#303]
Tried to update today and got several severe warnings/errors.
Here's the log: https://paste.yunohost.org/xituruqeke

It seems to be related to the newest 7.3 php-fpm upgrade which I did a few days ago, uploading to my instance isn't possible anymore because of redis-server issues, which I hoped to fix with this upgrade.

Running on a relatively new armbian release.

**Comment by kay0u** [comment]
Hi, from what I can see:

```
An unhandled exception has been thrown:
RedisException: Verbindungsaufbau abgelehnt in /var/www/nextcloud/lib/private/RedisFactory.php:92
Stack trace:
#0 /var/www/nextcloud/lib/private/RedisFactory.php(92): Redis->connect('localhost', '6379', '0.0')
#1 /var/www/nextcloud/lib/private/RedisFactory.php(108): OC\RedisFactory->create()
#2 /var/www/nextcloud/lib/private/Memcache/Redis.php(42): OC\RedisFactory->getInstance()
#3 /var/www/nextcloud/lib/private/Memcache/Factory.php(135): OC\Memcache\Redis->__construct('a75e171d29e947a...')
#4 /var/www/nextcloud/lib/private/Server.php(973): OC\Memcache\Factory->createLocking('lock')
#5 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#6 /var/www/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('OCP\\Lock\\ILocki...')
#7 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\ServerContainer->query('OCP\\Lock\\ILocki...')
#8 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#9 /var/www/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('LockingProvider')
#10 /var/www/nextcloud/lib/private/Server.php(1918): OC\ServerContainer->query('LockingProvider')
#11 /var/www/nextcloud/lib/private/Files/View.php(116): OC\Server->getLockingProvider()
#12 /var/www/nextcloud/lib/private/Server.php(253): OC\Files\View->__construct()
#13 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#14 /var/www/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('OCP\\Encryption\\...')
#15 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(162): OC\ServerContainer->query('OCP\\Encryption\\...')
#16 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#17 /var/www/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('EncryptionManag...')
#18 /var/www/nextcloud/lib/private/Server.php(1391): OC\ServerContainer->query('EncryptionManag...')
#19 /var/www/nextcloud/lib/base.php(841): OC\Server->getEncryptionManager()
#20 /var/www/nextcloud/lib/base.php(726): OC::registerEncryptionWrapper()
#21 /var/www/nextcloud/lib/base.php(1089): OC::init()
#22 /var/www/nextcloud/console.php(48): require_once('/var/www/nextcl...')
#23 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#24 {main}+ ynh_exit_properly
```

Is redis running?

`systemctl status redis`

**Comment by 1989gironimo** [comment]
Nope, I can't get it to run.

It throws this error: Failed to start Advanced key-value store.

**Comment by 1989gironimo** [comment]
The permissions went nuts after the upgrade of redis a few days before I found.
The /var/log/redis directory had root as the owner/group and not redis, fixed it with:
```
chown -R redis:redis /var/log/redis
chmod -R u+rwX,g+rwX,u+rx /var/log/redis
```
