### ISSUE TITLE
18.0.7 not running php-fpm7.3 can't access with internal server error

### ISSUE THREAD

**Issue by boistordu** [YunoHost-Apps/nextcloud_ynh#329]
Hi,

so as I've stated this is quite related to this issue: 
https://github.com/YunoHost-Apps/nextcloud_ynh/issues/313.
It seems that we are too easy on the depedencies with nextcloud.

Nextcloud 18.0.5 was running fine under php-fpm7.3 process. 
Then the upgrade happen and at the same time I had an upgrade of nginx and other depedencies. This is on a olimex lime 2 arm board.
In summary, nextcloud 18.0.7 have migrated the whole thing to php-fpm which is of course outdated for it and so I got a beautiful blue screen of internal server errorfrom nextcloud.
I've made a post here on yunohost forum:
https://forum.yunohost.org/t/nextcloud-unavailable-internal-server-error-since-nginx-upgrade/12544/9
So could be have an update asap to resolve this issue and have it transfered back to php-fpm7.3? 
If I try to run occ with php 7.3:
```
  sudo -u nextcloud php7.3 occ app:list
An unhandled exception has been thrown:
TypeError: Argument 1 passed to "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" must be an object, string given. in /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php:63
Stack trace:
#0 /var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(70): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('\\OCP\\Files::pre...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#1 /var/www/nextcloud/lib/private/Files/Node/Node.php(117): OC\EventDispatcher\SymfonyAdapter->dispatch('\\OCP\\Files::pre...', Object(Symfony\Component\EventDispatcher\GenericEvent))
#2 /var/www/nextcloud/lib/private/Files/Node/Folder.php(162): OC\Files\Node\Node->sendHooks(Array, Array)
#3 /var/www/nextcloud/lib/private/Files/AppData/AppData.php(158): OC\Files\Node\Folder->newFolder('templates')
#4 /var/www/nextcloud/apps/richdocuments/lib/TemplateManager.php(148): OC\Files\AppData\AppData->newFolder('templates')
#5 /var/www/nextcloud/apps/richdocuments/lib/TemplateManager.php(134): OCA\Richdocuments\TemplateManager->createAppDataFolders()
#6 [internal function]: OCA\Richdocuments\TemplateManager->__construct('richdocuments', NULL, Object(OC\AllConfig), Object(OC\Files\AppData\AppData), Object(OC\URLGenerator), Object(OC\Files\Node\LazyRoot), Object(OC\L10N\LazyL10N))
#7 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(83): ReflectionClass->newInstanceArgs(Array)
#8 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(100): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Richdocumen...')
#10 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(415): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Richdocumen...')
#11 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(386): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Richdocumen...')
#12 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(70): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Richdocumen...', true)
#13 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(100): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#14 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Richdocumen...')
#15 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(415): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Richdocumen...')
#16 /var/www/nextcloud/lib/private/ServerContainer.php(134): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Richdocumen...')
#17 /var/www/nextcloud/lib/private/Console/Application.php(220): OC\ServerContainer->query('OCA\\Richdocumen...')
#18 /var/www/nextcloud/lib/private/Console/Application.php(135): OC\Console\Application->loadCommandsFromInfoXml(Array)
#19 /var/www/nextcloud/console.php(98): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#21 {main}root@dev:/var/www/nextcloud# 
```
So I can't even investigate if a plugin is running haywire.

**Comment by kay0u** [comment]
Hi,

Can you try to move the folder `/var/www/nextcloud/apps/richdocuments` away (do not delete it), and try again?

**Comment by boistordu** [comment]
Okey the occ is working again! Great improvements thanks. Now I can deal with it efficiently to debug this. I didn't want to try to move or delete any folder before to not cause catastrophic failure. That's why I wanted to have an input of someone more used to it. 

Very thanksfull to you @kay0u  I now can do some research and post my findings and try to resolve it

**Comment by boistordu** [comment]
Okey so it was geoblocker or suspicious login . One of both of them. Suspicious login was one version behind at 3.2 in place of 3.2.1, so maybe it was a bug of that.

Thanks for the help
