### ISSUE TITLE
Impossible to upgrade nextcloud + system lost track of nextcloud presence

### ISSUE THREAD

**Issue by changemenemo** [YunoHost-Apps/nextcloud_ynh#337]
Hi,

I'm sorry in advance to take precious time and ressources of the maintainers of this customized version of this webapp for nextcloud but it seems that nobody can help me on the [forum](https://forum.yunohost.org/t/partition-tmp-contents-nextcloud-unrecognized-by-the-system-after-failed-upgrade/12769). 

That's what happened during the migration of nextcloud from 18.0.7 to 19.0.3.

```
Warning: cp: error writing '/tmp/yunohost_remove/manifest.json': No space left on device
Warning: cp: error writing '/tmp/yunohost_remove/settings.yml': No space left on device
Warning: 2395100 /usr/share/yunohost/helpers.d/setting: line 74: cannot create temp file for here-document: No space left on device
Warning: 2396676 /usr/share/yunohost/helpers.d/setting: line 74: cannot create temp file for here-document: No space left on device
Warning: 2398094 /usr/share/yunohost/helpers.d/setting: line 74: cannot create temp file for here-document: No space left on device
Warning: 2399290 /usr/share/yunohost/helpers.d/setting: line 74: cannot create temp file for here-document: No space left on device
Warning: 2400496 /usr/share/yunohost/helpers.d/setting: line 74: cannot create temp file for here-document: No space left on device
Warning: 2401854 /usr/share/yunohost/helpers.d/setting: line 74: cannot create temp file for here-document: No space left on device
Warning: 2417670 usage: yunohost domain url-available domain path [-h]
Warning: 2417672 yunohost domain url-available: error: too few arguments
Warning: 2419259 Path not available:
Warning: 2419944 Could not restore nextcloud
Warning: Traceback (most recent call last):
Warning:   File "/usr/lib/moulinette/yunohost/backup.py", line 1407, in _restore_app
Warning:     env=env_dict)[0]
Warning:   File "/usr/lib/moulinette/yunohost/hook.py", line 347, in hook_exec
Warning:     raise YunohostError('hook_exec_failed', path=path)
Warning: YunohostError: Could not run script: /var/tmp/restore0a5dff/restore
Warning: 2421145 Here's an extract of the logs before the crash. It might help debugging the error:
Warning: 2431022 /usr/share/yunohost/helpers.d/setting: line 74: cannot create temp file for here-document: No space left on device
Warning: 2432554 /usr/share/yunohost/helpers.d/setting: line 74: cannot create temp file for here-document: No space left on device
Warning: 2434537 /usr/share/yunohost/helpers.d/setting: line 74: cannot create temp file for here-document: No space left on device
Warning: 2452406 /usr/share/yunohost/helpers.d/apt: line 15: cannot create temp file for here-document: No space left on device
Warning: 2995231 ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
Warning: 3002549 ynh_secure_remove called with empty argument, ignoring.
Warning: 3272006 Nothing was restored
Warning: The app was restored to the way it was before the failed upgrade.
Error: Could not upgrade nextcloud: An error occurred inside the app upgrade script
Info: The operation 'Upgrade the 'nextcloud' app' could not be completed. Please share the full log of this operation using the command 'yunohost log display 20200925-021555-app_upgrade-nextcloud --share' to get help
Warning: Here's an extract of the logs before the crash. It might help debugging the error:
Info: DEBUG - 176193 ++ ynh_app_setting_get --app=nextcloud --key=do_not_backup_data
Info: DEBUG - 176534 ++ ynh_app_setting get nextcloud do_not_backup_data
Info: DEBUG - 176536 ++ [[ get == \d\e\l\e\t\e ]]
Info: DEBUG - 176538 ++ ACTION=get
Info: DEBUG - 176540 ++ APP=nextcloud
Info: DEBUG - 176552 ++ KEY=do_not_backup_data
Info: DEBUG - 176554 ++ VALUE=
Info: DEBUG - 176556 ++ python2.7 -
Info: DEBUG - 177500 ++ [[ do_not_backup_data =~ ^(unprotected|skipped)_ ]]
Info: DEBUG - 177502 + do_not_backup_data=
Info: DEBUG - 177506 + '[' 1 -eq 1 ']'
Info: DEBUG - 177511 + '[' 0 -eq 1 ']'
Info: DEBUG - 177514 + '[' 1 -eq 1 ']'
Info: DEBUG - 177524 + '[' 1 -eq 1 ']'
Info: DEBUG - 177532 + ynh_print_warn '--message=/home/yunohost.app/nextcloud/data will not be saved, because '\''BACKUP_CORE_ONLY'\'' is set.'
Info: DEBUG - 177668 + ynh_print_log '/home/yunohost.app/nextcloud/data will not be saved, because '\''BACKUP_CORE_ONLY'\'' is set.'
Info: WARNING - 177670 /home/yunohost.app/nextcloud/data will not be saved, because 'BACKUP_CORE_ONLY' is set.
Info: DEBUG - 177683 + echo -e '/home/yunohost.app/nextcloud/data will not be saved, because '\''BACKUP_CORE_ONLY'\'' is set.'
Info: DEBUG - 177685 + return 0
Info: DEBUG - 178204 + echo '[####################] > Backup script completed for nextcloud. (YunoHost will then actually copy those files to the archive).'
Info: DEBUG - 178208 + ynh_exit_properly
Error: The app 'nextcloud' failed to upgrade, and as a consequence the following apps' upgrades have been cancelled: nextcloud, alltube
Warning: unable to upgrade apps: The operation 'Upgrade the 'nextcloud' app' could not be completed. Please share the full log of this operation using the command 'yunohost log display 20200925-021555-app_upgrade-nextcloud --share' to get help
Error: Some apps could not be upgraded

```

As you can see the /tmp partition was too small. (Independent of my will since I've installed yunohost through a script of net neutrality's NGO which apparently configured it with a 500MB partition for /tmp) 
But after that, the process moulinette as you can see just crashed and so even if the process exited normally at the very end, the process was unable because of the crash explicited above to restore the nextcloud installation. 
Which resulted after reboot of the inability of the system to recognize that nextcloud is in fact installed on the system as described [here](https://paste.yunohost.org/raw/ojacixegeq)
So since of course everything in the tmp partition disappeared, is there a way to actually say to the system that nextcloud still exist and so that it should be restored or upgraded or do I need to start from scratch this nextcloud installation by removing then the /var/www/nextcloud an so all my settings and apps which were installed in it?

Thanks in advance for all the help you could provide

**Comment by boistordu** [comment]
Restauration did help each time but the fact that /tmp tmpfs partition on arm bord with armbian distribution makes freeze the system each time is full and so moulinette it's really frustrating. 
Can we do something about that? 

The tmp partition of 500MB is largely full with a standard installation with some security plug-ins because of all the js files that needs to be replaced. So when you add several plug-ins like element, maps, phonesync, phonetrack, gpxpod or others, each of them makes the installation too big. Not of all them at once, just each of them(will edit later with some screen).

So it would be maybe préférable that we could make a script that disable the plug-ins, removes them completely or find another place to store them when upgrading the webapp if possible.

**Comment by tituspijean** [comment]
Closing, as the issue is stale and a tad too specific to partition size. Feel free to reopen if needed.
