### ISSUE TITLE
Installed tesseract-ocr leads to error while upgrading from von 18.0.7~ynh1 to 19.0.3~ynh1 

### ISSUE THREAD

**Issue by 1989gironimo** [YunoHost-Apps/nextcloud_ynh#339]
Tried to update twice, but it always leads to an error pointing to an error regarding tesseract-ocr.
Here's the log output: https://paste.yunohost.org/raw/axigehanuf

Here's the extract from the log, where the error is mentioned:
```
2020-10-03 13:23:51,611: DEBUG - Cleanup ocr app data folder.
2020-10-03 13:23:51,613: WARNING -  Starting ...
2020-10-03 13:23:51,615: DEBUG - 
2020-10-03 13:23:53,929: DEBUG - An unhandled exception has been thrown:
2020-10-03 13:23:53,929: DEBUG - TypeError: Argument 1 passed to Symfony\Component\Console\Helper\ProgressBar::advance() must be of the type int, string given, called in /var/www/nextcloud/core/Command/Upgrade.php on line 144 and defined in /var/www/nextcloud/3rdparty/symfony/console/Helper/ProgressBar.php:310
2020-10-03 13:23:53,930: DEBUG - Stack trace:
2020-10-03 13:23:53,931: DEBUG - #0 /var/www/nextcloud/core/Command/Upgrade.php(144): Symfony\Component\Console\Helper\ProgressBar->advance('Deleted tessdat...')
2020-10-03 13:23:53,931: DEBUG - #1 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(264): OC\Core\Command\Upgrade->OC\Core\Command\{closure}(Object(Symfony\Component\EventDispatcher\GenericEvent), '\\OC\\Repair::adv...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
2020-10-03 13:23:53,932: DEBUG - #2 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, '\\OC\\Repair::adv...', Object(Symfony\Component\EventDispatcher\GenericEvent))
2020-10-03 13:23:53,933: DEBUG - #3 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, '\\OC\\Repair::adv...', Object(Symfony\Component\EventDispatcher\GenericEvent))
2020-10-03 13:23:53,933: DEBUG - #4 /var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(70): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\EventDispatcher\GenericEvent), Object(Symfony\Component\EventDispatcher\GenericEvent))
2020-10-03 13:23:53,934: DEBUG - #5 /var/www/nextcloud/lib/private/Repair.php(201): OC\EventDispatcher\SymfonyAdapter->dispatch('\\OC\\Repair::adv...', Object(Symfony\Component\EventDispatcher\GenericEvent))
2020-10-03 13:23:53,934: DEBUG - #6 /var/www/nextcloud/lib/private/Repair.php(232): OC\Repair->emit('\\OC\\Repair', 'advance', Array)
2020-10-03 13:23:53,935: DEBUG - #7 /var/www/nextcloud/apps/ocr/lib/Migration/CleanupTessdata.php(48): OC\Repair->advance('Deleted tessdat...')
2020-10-03 13:23:53,936: DEBUG - #8 /var/www/nextcloud/lib/private/Repair.php(103): OCA\Ocr\Migration\CleanupTessdata->run(Object(OC\Repair))
2020-10-03 13:23:53,936: DEBUG - #9 /var/www/nextcloud/lib/private/legacy/OC_App.php(976): OC\Repair->run()
2020-10-03 13:23:53,937: DEBUG - #10 /var/www/nextcloud/lib/private/App/AppManager.php(412): OC_App::executeRepairSteps('ocr', Array)
2020-10-03 13:23:53,937: DEBUG - #11 /var/www/nextcloud/lib/private/Updater.php(410): OC\App\AppManager->disableApp('ocr', true)
2020-10-03 13:23:53,938: DEBUG - #12 /var/www/nextcloud/lib/private/Updater.php(253): OC\Updater->checkAppsRequirements()
2020-10-03 13:23:53,938: DEBUG - #13 /var/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade('19.0.0.12', '18.0.7.1')
2020-10-03 13:23:53,939: DEBUG - #14 /var/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
2020-10-03 13:23:53,940: DEBUG - #15 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-10-03 13:23:53,940: DEBUG - #16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-10-03 13:23:53,941: DEBUG - #17 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-10-03 13:23:53,942: DEBUG - #18 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-10-03 13:23:53,942: DEBUG - #19 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2020-10-03 13:23:53,943: DEBUG - #20 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
2020-10-03 13:23:53,944: DEBUG - #21 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
2020-10-03 13:23:53,944: DEBUG - #22 {main}+ '[' 1 -eq 3 ']'
2020-10-03 13:23:53,945: DEBUG - + ynh_die '--message=Unable to upgrade Nextcloud'
2020-10-03 13:23:54,050: DEBUG - + ret_code=1
```

**Comment by 1989gironimo** [comment]
Had to remove (not disable!) every app which pointed to the full text search, after that, the update went through, finally.
