### ISSUE TITLE
Scan files fails due to symlink not followed

### ISSUE THREAD

**Issue by moutonjr** [YunoHost-Apps/nextcloud_ynh#345]
Hello team,

Since https://github.com/nextcloud/server/issues/20592, the NextCloud file scan does not follow symlinks. I'm pretty sure that there is a YNH workaround, yet my %USER%/Multimedia is borken after manual update "Forbidden operation"

Either there is a wrapped (yet unknown to myself) command to update, or there is a bug ? This is blocking my prod instance as my multimedia files disappeared.

Intended : 
`# sudo -su nextcloud php7.3 /var/www/nextcloud/occ files:scan MYUSER`

Expected : 
All files scanned. MYUSER files available from WebUI.

Got:
```
Starting scan for user 1 out of 1 (MYUSER)
Exception during scan: Following symlinks is not allowed
#0 /var/www/nextcloud/lib/private/Files/Storage/Local.php(161): OC\Files\Storage\Local->getSourcePath('/Share')
#1 /var/www/nextcloud/lib/private/Files/Storage/Common.php(884): OC\Files\Storage\Local->getMetaData('/Share')
#2 [internal function]: OC\Files\Storage\Common->getDirectoryContent('')
#3 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(408): iterator_to_array(Object(Generator))
#4 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(388): OC\Files\Cache\Scanner->handleChildren('', true, 3, 286839, true, 0)
#5 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(340): OC\Files\Cache\Scanner->scanChildren('', true, 3, 286839, true)
#6 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(260): OC\Files\Cache\Scanner->scan('', true, 3)
#7 /var/www/nextcloud/apps/files/lib/Command/Scan.php(151): OC\Files\Utils\Scanner->scan('/kifof', true, NULL)
#8 /var/www/nextcloud/apps/files/lib/Command/Scan.php(207): OCA\Files\Command\Scan->scanFiles('kifof', '/kifof', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#9 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1012): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#16 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#17 {main}
```

Version: nextcloud 19.0.3~ynh1 from yunohost 4.0.8

**Comment by kay0u** [comment]
Hi,

The workaround i found is to:

- Remove the symlink "Share" in the folder "Multimedia" on each users
- Change line 60 of the file `/var/www/nextcloud/lib/private/Files/Storage/Local.php` into `protected $allowSymlinks = true;`

The is an issue about the "risks" of allowing symlinks [here](https://github.com/nextcloud/server/issues/1257)

Ping @YunoHost-Apps/apps-group do you have any idea?

**Comment by moutonjr** [comment]
Acknowledge the workaround (and associated security issue)
I'm eager to look forward the fix though.

Thank you @kay0u

**Comment by yalh76** [comment]
> Ping @YunoHost-Apps/apps-group do you have any idea?

no idea :/

**Comment by benneti** [comment]
Came accross this issue, too. Simply deleting is probably the simplest for now, while not elegant.

**Comment by adocampo** [comment]
I need as well the possibility to follow symlinks created by the root, so I had to change Local.php which is not ideal at all.
I'm upvoting for a config.php option so we can upgrade safely.

**Comment by jkufner** [comment]
The failure due to an existing symlink is a wrong behavior regardless the Nextcloud's approach to the symlinks. They should be either ignored or followed, but it should not crash with an exception just because a symlink is found.

**Comment by artybdrlt** [comment]
@kay0u I saw you merged the commit "Allow symlinks" but I don't see it now in the master branch. Did you give up on allowing symlinks in the end?
