### ISSUE TITLE
upgrade 22.2.10 ->25.0.3 error : PHP version

### ISSUE THREAD

**Issue by kicroc2000** [YunoHost-Apps/nextcloud_ynh#554]
Hello, I got a problem with my upgrade. It seems that during the process, my server is updated from php 7.4 to 8.1, and then there is a version check telling that this nextcloud version is not compatible with php > v8

> 2023-01-28 16:35:24,022: DEBUG - + '[' UPGRADE_APP == UPGRADE_APP ']'
2023-01-28 16:35:24,162: INFO - [#############+......] > Upgrading Nextcloud...
2023-01-28 16:35:24,163: DEBUG - + source upgrade.d/upgrade.last.sh
2023-01-28 16:35:24,163: DEBUG - ++ next_version=25.0.3
2023-01-28 16:35:24,164: DEBUG - ++ nextcloud_source_sha256=4b2b1423736ef92469096fe24f61c24cad87a34e07c1c7a81b385d3ea25c00ec
2023-01-28 16:35:24,164: DEBUG - + last_version=25.0.3
2023-01-28 16:35:24,164: DEBUG - + last_major_version=25
2023-01-28 16:35:24,164: DEBUG - + chown -R nextcloud: /var/www/nextcloud /home/yunohost.app/nextcloud/data
2023-01-28 16:35:25,219: DEBUG - + exec_occ -V
2023-01-28 16:35:25,220: DEBUG - + '[' 22 = last ']'
2023-01-28 16:35:25,220: DEBUG - + '[' 22 -ge 15 ']'
2023-01-28 16:35:25,221: DEBUG - + NEXTCLOUD_PHP_VERSION=8.1
2023-01-28 16:35:25,222: DEBUG - + cd /var/www/nextcloud
2023-01-28 16:35:25,222: DEBUG - + ynh_exec_as nextcloud php8.1 --define apc.enable_cli=1 occ --no-interaction --no-ansi -V
2023-01-28 16:35:25,222: DEBUG - + local user=nextcloud
2023-01-28 16:35:25,223: DEBUG - + shift 1
2023-01-28 16:35:25,223: DEBUG - ++ whoami
2023-01-28 16:35:25,225: DEBUG - + [[ nextcloud = root ]]
2023-01-28 16:35:25,225: DEBUG - + sudo -u nextcloud php8.1 --define apc.enable_cli=1 occ --no-interaction --no-ansi -V
2023-01-28 16:35:25,335: DEBUG - This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.14.+ ynh_exit_properly
2023-01-28 16:35:25,336: DEBUG - + local exit_code=255
2023-01-28 16:35:25,338: DEBUG - + '[' 255 -eq 0 ']'
2023-01-28 16:35:25,843: DEBUG - + ynh_clean_setup
2023-01-28 16:35:25,843: DEBUG - + ynh_restore_upgradebackup
2023-01-28 16:35:25,843: DEBUG - + ynh_print_err '--message=Upgrade failed.'
2023-01-28 16:35:25,867: DEBUG - + ynh_print_log '[Error] Upgrade failed.'
2023-01-28 16:35:25,867: DEBUG - + echo -e '[Error] Upgrade failed.'
2023-01-28 16:35:25,867: DEBUG - + local app_bck=nextcloud
2023-01-28 16:35:25,868: DEBUG - + NO_BACKUP_UPGRADE=0
2023-01-28 16:35:25,868: WARNING - [Error] Upgrade failed.
2023-01-28 16:35:25,871: DEBUG - + ynh_backup_archive_exists nextcloud-pre-upgrade2
2023-01-28 16:35:25,871: DEBUG - + yunohost backup list --output-as json --quiet
2023-01-28 16:35:25,872: DEBUG - + jq -e --arg archive nextcloud-pre-upgrade2 '.archives | index($archive)'
2023-01-28 16:35:26,341: DEBUG - + yunohost app remove nextcloud
2023-01-28 16:35:26,759: DEBUG - Suppression de nextcloud...
2023-01-28 16:35:27,217: DEBUG - [....................] > Loading installation settings...
2023-01-28 16:35:28,060: DEBUG - [+++++++++...........] > Removing dependencies...
2023-01-28 16:35:51,348: DEBUG - [#########+++........] > Removing the MySQL database...
2023-01-28 16:35:53,506: DEBUG - [############+.......] > Removing app main directory...
2023-01-28 16:35:55,751: DEBUG - [#############.......] > Removing NGINX web server configuration...
2023-01-28 16:36:36,439: DEBUG - [#############+......] > Removing PHP-FPM configuration...
2023-01-28 16:36:39,323: WARNING - E: Unable to locate package nextcloud-ynh-deps
2023-01-28 16:36:39,419: DEBUG - [##############+.....] > Removing logrotate configuration...
2023-01-28 16:36:39,565: DEBUG - [###############+++..] > Removing Fail2Ban configuration...
2023-01-28 16:36:40,845: DEBUG - [##################+.] > Removing the dedicated system user...
2023-01-28 16:36:41,345: DEBUG - [####################] > Removal of nextcloud completed

Im a not sure, but may I propose
`sudo -u nextcloud php8.1 --define apc.enable_cli=1 occ --no-interaction --no-ansi -V`
be replaced by
`sudo -u nextcloud php7.4 --define apc.enable_cli=1 occ --no-interaction --no-ansi -V`
when the installed  nextcloud package is too old to support php 8 ?

Otherwise, is there is a way to get nextcloud 23 & 24 tarball to upgrade in command line ?

best regards

**Comment by ericgaspar** [comment]
There is a [PR](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/526) that solves migration from "old" Nextcloud version to 25.0.3.
If you want to try:
```
sudo yunohost app upgrade nextcloud -u https://github.com/SquirrelMe/nextcloud_ynh
```

**Comment by kicroc2000** [comment]
Hello : i still have the issue while testing what you suggested : 

> Info: DEBUG - This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.14.+ ynh_exit_properly
> Error: The operation 'Upgrade the 'nextcloud' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20230130-210127-app_upgrade-nextcloud' to get help

the corrective version works up to 22.2.10 not included from what i read in the solution 2 descripted ,but it seems that 22.2.10 is also impacted

best regards

**Comment by ericgaspar** [comment]
Do you still have this issue with 25.0.3~ynh3?

**Comment by kicroc2000** [comment]
Hello, after a reboot of the server and a retry, I have still an error : the upgrade 22-> 23 seems ok, but 23-> 24 ends on error : 
https://paste.yunohost.org/raw/iwofereqej
---------------------
```
Info: DEBUG - Error: Undefined class constant 'MIGRATION_24' in /var/www/nextcloud/apps/fulltextsearch/lib/Migration/Version2400Date202201301329.php:159
Info: DEBUG - Stack trace:
Info: DEBUG - #0 /var/www/nextcloud/lib/private/DB/MigrationService.php(547): OCA\FullTextSearch\Migration\Version2400Date202201301329->postSchemaChange()
Info: DEBUG - #1 /var/www/nextcloud/lib/private/DB/MigrationService.php(425): OC\DB\MigrationService->executeStep()
Info: DEBUG - #2 /var/www/nextcloud/lib/private/legacy/OC_App.php(1022): OC\DB\MigrationService->migrate()
Info: DEBUG - #3 /var/www/nextcloud/lib/private/Installer.php(201): OC_App::updateApp()
Info: DEBUG - #4 /var/www/nextcloud/lib/private/Updater.php(415): OC\Installer->updateAppstoreApp()
Info: DEBUG - #5 /var/www/nextcloud/lib/private/Updater.php(277): OC\Updater->upgradeAppStoreApps()
Info: DEBUG - #6 /var/www/nextcloud/lib/private/Updater.php(133): OC\Updater->doUpgrade()
Info: DEBUG - #7 /var/www/nextcloud/core/Command/Upgrade.php(235): OC\Updater->upgrade()
Info: DEBUG - #8 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
Info: DEBUG - #9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
Info: DEBUG - #10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
Info: DEBUG - #11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
Info: DEBUG - #12 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
Info: DEBUG - #13 /var/www/nextcloud/console.php(99): OC\Console\Application->run()
Info: DEBUG - #14 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
Info: DEBUG - #15 {main}+ '[' 1 -eq 3 ']'
```

best regards

**Comment by ericgaspar** [comment]
try to deactivate `fulltextsearch` app before upgrading

**Comment by kicroc2000** [comment]
Hello Eric, `fulltextsearch` deactivated, and all went smoothly. Thank you very much for your help
regards
