### ISSUE TITLE
After 29.0.2 upgrade "Doctrine\DBAL\Exception: Failed to connect to the database" and "Internal Server Error"

### ISSUE THREAD

**Issue by MrTastyBiscuits** [YunoHost-Apps/nextcloud_ynh#709]
### Describe the bug

I upgraded successfully to 29.0.2 and Nextcloud was working properly after the upgrade.
When I tried to access Nextcloud this morning, I got this error text on the root nextcloud domain:

<details open>
  <summary>Error displayed in web browser</summary>
 
  ```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
  ```
</details>

The YunoHost page for the app also displays some error (see below under logs).
From what I was able to find online, it seems to be related to some sort of php upgrade and dependencies. Maybe related to unattended upgrades (?). 
I have not changed anything on the server since installing the update.
Unfortunately, I am not competent enough to understand how to solve that. 
Any help would be greatly appreciated.
Let me know if any further details are required.

### Context

- Hardware: *Hetzner VPS*
- YunoHost version: 11.2.23
- I have access to my server: *Through SSH and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *latest*

### Steps to reproduce

- Perform 29.0.2 upgrade
- Reboot server

### Expected behavior
Nextcloud should start properly and be accessible, as it was right after the update.

### Logs

<details open>
  <summary>Yunohost Web Admin for Nextcloud</summary>
  
Sorry for the formatting, it is display this way in a red box in the webadmin.
  ```
An error prevents the configuration panel from being displayed:

Could not read return from hook /etc/yunohost/apps/nextcloud/scripts/config. Error: Corrupted YAML read from /tmp/tmpyr79kd5j/stdreturn (reason: mapping values are not allowed here<br> in "<unicode string>", line 9, column 66:<br> ... thrown: Doctrine\DBAL\Exception: Failed to connect to the datab ... <br> ^). Raw content: fpm_footprint:<br> high<br>fpm_free_footprint:<br> 0<br>fpm_usage: 'medium'<br>maintenance_mode:<br> <br>system_addressbook_exposed:<br> An unhandled exception has been thrown: Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: could not find driver in /var/www/nextcloud/lib/private/DB/Connection.php:163 Stack trace: #0 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(453): OC\DB\Connection->connect() #1 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(411): Doctrine\DBAL\Connection->getDatabasePlatformVersion() #2 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(318): Doctrine\DBAL\Connection->detectDatabasePlatform() #3 /var/www/nextcloud/lib/private/DB/ConnectionAdapter.php(200): Doctrine\DBAL\Connection->getDatabasePlatform() #4 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(121): OC\DB\ConnectionAdapter->getDatabasePlatform() #5 /var/www/nextcloud/lib/private/AppConfig.php(1237): OC\DB\QueryBuilder\QueryBuilder->expr() #6 /var/www/nextcloud/lib/private/AppConfig.php(262): OC\AppConfig->loadConfig() #7 /var/www/nextcloud/lib/private/AppConfig.php(1378): OC\AppConfig->searchValues() #8 /var/www/nextcloud/lib/private/App/AppManager.php(131): OC\AppConfig->getValues() #9 /var/www/nextcloud/lib/private/App/AppManager.php(152): OC\App\AppManager->getInstalledAppsValues() #10 /var/www/nextcloud/lib/private/legacy/OC_App.php(234): OC\App\AppManager->getInstalledApps() #11 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC_App::getEnabledApps() #12 /var/www/nextcloud/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration() #13 /var/www/nextcloud/lib/base.php(1181): OC::init() #14 /var/www/nextcloud/console.php(48): require_once('...') #15 /var/www/nextcloud/occ(11): require_once('...') #16 {main}<br>

Please report this error to the YunoHost team to get it fixed!
  ```
</details>

<details open>
  <summary>When running any OCC command</summary>
 
  ```
nextcloud@y:~$ php occ upgrade
An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: could not find driver in /var/www/nextcloud/lib/private/DB/Connection.php:163
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(453): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(411): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(318): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/nextcloud/lib/private/DB/ConnectionAdapter.php(200): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(121): OC\DB\ConnectionAdapter->getDatabasePlatform()
#5 /var/www/nextcloud/lib/private/AppConfig.php(1237): OC\DB\QueryBuilder\QueryBuilder->expr()
#6 /var/www/nextcloud/lib/private/AppConfig.php(262): OC\AppConfig->loadConfig()
#7 /var/www/nextcloud/lib/private/AppConfig.php(1378): OC\AppConfig->searchValues()
#8 /var/www/nextcloud/lib/private/App/AppManager.php(131): OC\AppConfig->getValues()
#9 /var/www/nextcloud/lib/private/App/AppManager.php(152): OC\App\AppManager->getInstalledAppsValues()
#10 /var/www/nextcloud/lib/private/legacy/OC_App.php(234): OC\App\AppManager->getInstalledApps()
#11 /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(90): OC_App::getEnabledApps()
#12 /var/www/nextcloud/lib/base.php(706): OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
#13 /var/www/nextcloud/lib/base.php(1181): OC::init()
#14 /var/www/nextcloud/console.php(48): require_once('...')
#15 /var/www/nextcloud/occ(11): require_once('...')
  ```
</details>

**Comment by rodinux** [comment]
You see these massages when the service php-fpm failed...

**Comment by kay0u** [comment]
You can't run `php occ upgrade` like that, but: `sudo -u nextcloud php8.2 --define apc.enable_cli=1 occ upgrade` (or php8.3, I'm not sure).

There is a regression in this package right know, I'm trying to solve it in testing:

https://github.com/YunoHost-Apps/nextcloud_ynh/pull/693

**Comment by kay0u** [comment]
Can you try the same with php8.3 please?

**Comment by kay0u** [comment]
Yep, that's the current issue in the stable version

You can get more information in this issue https://github.com/YunoHost-Apps/nextcloud_ynh/issues/708

**Comment by kay0u** [comment]
You're welcome, the current testing is not that far from being stable anyway, I'm just waiting for the bookworm CI
