### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by SylvainCecchetto** [YunoHost-Apps/nextcloud_ynh#82]
Hi,
After a fresh YunoHost server install I want to try NextCloud but on my browser I only get this message error. Do someone know where we can find any log?

Thanks!

<img width="824" alt="capture d ecran 2018-01-16 a 15 43 47" src="https://user-images.githubusercontent.com/11562279/34994516-1077b0dc-fad4-11e7-9dd9-a054e78edabf.png">

**Comment by JimboJoe** [comment]
Hi,
You  can have a look at these log files:
* web server error logs: /var/log/nginx/yourdomain.tld-errors.log
* Nextcloud logs /home/yunohost.app/nextcloud/data/nextcloud.log

**Comment by SylvainCecchetto** [comment]
Thank you!
It seems to be a database error according to the Nginx log
```
2018/01/17 07:46:16 [error] 1044#0: *30 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver:2018/01/17 09:20:42 [error] 1067#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in /var/www/nextcloud/lib/private/DB/Connection.php:61
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/nextcloud/lib/private/DB/Connection.php(148): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doct...
PHP message: PHP Fatal error:  Uncaught exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)' in /var/www/nextcloud/lib/private/DB/Connection.php:61
Stack trace:
#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/nextcloud/lib/private/DB/Connection.php(148): Doctrine\DBAL\Connection->setTransactionIsola
```

The only thing that I installed before Nextcloud is Matrix-Synapse

**Comment by JimboJoe** [comment]
So, how is MySQL/MariaDB behaving?
* `systemctls status mysql`
* `/var/log/mysql.err/log` or `/var/log/mysql/error.log`

**Comment by SylvainCecchetto** [comment]
* mysql service is active and running
```
● mysql.service - LSB: Start and stop the mysql database server daemon
   Loaded: loaded (/etc/init.d/mysql)
   Active: active (running) since mer. 2018-01-17 09:23:08 CET; 2h 33min ago
  Process: 1080 ExecStart=/etc/init.d/mysql start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/mysql.service
           ├─1221 /bin/bash /usr/bin/mysqld_safe
           └─1482 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/lib/mysql/acer.err --pid-file=acer.pid --socket=/var/run/mysqld...

janv. 17 09:22:55 acer systemd[1]: Starting LSB: Start and stop the mysql database server daemon...
janv. 17 09:23:08 acer mysql[1080]: Starting MariaDB database server: mysqld . . . . . . . . ..
janv. 17 09:23:08 acer systemd[1]: Started LSB: Start and stop the mysql database server daemon.
janv. 17 09:23:09 acer /etc/mysql/debian-start[1865]: Triggering myisam-recover for all MyISAM tables
```
* Nothing in all of the mysql log files

**Comment by JimboJoe** [comment]
Based on your log, it seems MySQL error messages are located in `/var/lib/mysql/acer.err`.
Otherwise, maybe try to restart mysql anyway... ?

**Comment by SylvainCecchetto** [comment]
So, after uninstalled and re installed Nextcloud everything seems to be OK ...
I don't know why, maybe a file corruption?

Sorry for this "false" issue and thank you for your help ;-)
