### ISSUE TITLE
Internal error on a fresh install : users folder have wrong permissions

### ISSUE THREAD

**Issue by SiM** [YunoHost-Apps/nextcloud_ynh#98]
I have an Internal error after a fresh install of Nextcloud (12.0.5) (on a fresh Yunohost 2.7.10).

In /home/yunohost.app/nextcloud/data/nextcloud.log, I have : 
```
{"reqId":"6j70sXXCAcnNdn3trLBy","level":3,"time":"2018-03-12T12:14:41+00:00","remoteAddr":"10.0.2.100","user":"simon","app":"PHP","method":"GET","url":"\/nextcloud\/","message":"opendir(\/home\/yunohost.app\/nextcloud\/data\/simon\/cache): failed to open dir: No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#118","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}

{"reqId":"6j70sXXCAcnNdn3trLBy","level":3,"time":"2018-03-12T12:14:41+00:00","remoteAddr":"10.0.2.100","user":"simon","app":"index","method":"GET","url":"\/nextcloud\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(176): OC\\\\Files\\\\Node\\\\Node->checkPermissions(4)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/util.php(418): OC\\\\Files\\\\Node\\\\Folder->newFile('Nextcloud.mp4')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/util.php(388): OC_Util::copyr('\\\/var\\\/www\\\/nextcl...', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(489): OC_Util::copySkeleton('simon', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(361): OC\\\\User\\\\Session->prepareUserLogin(true, false)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(550): OC\\\\User\\\\Session->completeLogin(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(326): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(400): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Session.php(511): OC\\\\User\\\\Session->logClientIn(*** sensitive parameters replaced ***)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1058): OC\\\\User\\\\Session->tryBasicAuthLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request), Object(OC\\\\Security\\\\Bruteforce\\\\Throttler))\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(993): OC::handleLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))\\n#13 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:58.0) Gecko\/20100101 Firefox\/58.0","version":"12.0.5.3"}
```

Indeed, users folders haven't the right permissions, they belongs to "root" instead of "nextcloud".
I suppose it's why 'cache' and 'files' subfolders weren't created.

I tried to do several installation on this instance, and the same behaviour occurred around 15 times. 2 times the installations worked (one with the web gui install, one with CLI), but I didn't found any reason or any way to reproduce it.

I'm not the only one facing this problem : https://forum.yunohost.org/t/nextcloud-erreur-de-connexion/4159 (french)

```
yunohost: 
  repo: stable
  version: 2.7.10
yunohost-admin: 
  repo: stable
  version: 2.7.7
moulinette: 
  repo: stable
  version: 2.7.7
ssowat: 
  repo: stable
  version: 2.7.7
```

**Comment by JimboJoe** [comment]
Finally got this issue sorted out and made a PR [here](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/119), thanks to your precise analysis!
The problem was totally linked to the bad ownership of `/home/yunohost.app/nextcloud/data/USER` directory.

The issue is very old: at installation, a data folder was historically created for every existing YunoHost user (and created for any new user via a hook)... but the rights weren't good!

The issue was solved on de-installation/reinstallation because the ownership was globally set on `/home/yunohost.app/nextcloud` directory, which isn't deleted on de-installation.

The final word is that we don't need to create this directory as Nextcloud automatically creates it... :innocent:
